'''
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

   Begin     : 2012-07-01
   Copyright : (C) 2012 Go Sato 
   Email     : go.sato@zaq1.net
*********************************************************************
'''

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(400, 478)
        self.okOrCancel = QtGui.QDialogButtonBox(Dialog)
        self.okOrCancel.setGeometry(QtCore.QRect(310, 420, 81, 21))
        self.okOrCancel.setOrientation(QtCore.Qt.Horizontal)
        self.okOrCancel.setStandardButtons(QtGui.QDialogButtonBox.Cancel)
        self.okOrCancel.setObjectName(_fromUtf8("okOrCancel"))
        self.selectQGisLayer = QtGui.QComboBox(Dialog)
        self.selectQGisLayer.setGeometry(QtCore.QRect(130, 10, 251, 22))
        self.selectQGisLayer.setObjectName(_fromUtf8("selectQGisLayer"))
        self.label0 = QtGui.QLabel(Dialog)
        self.label0.setGeometry(QtCore.QRect(20, 10, 101, 16))
        self.label0.setObjectName(_fromUtf8("label0"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 280, 381, 131))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.originLongitudeField = QtGui.QDoubleSpinBox(self.groupBox)
        self.originLongitudeField.setGeometry(QtCore.QRect(110, 20, 81, 20))
        self.originLongitudeField.setWrapping(False)
        self.originLongitudeField.setDecimals(7)
        self.originLongitudeField.setMinimum(-180.0)
        self.originLongitudeField.setMaximum(180.0)
        self.originLongitudeField.setObjectName(_fromUtf8("originLongitudeField"))
        self.label1 = QtGui.QLabel(self.groupBox)
        self.label1.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.label1.setObjectName(_fromUtf8("label1"))
        self.originScale = QtGui.QDoubleSpinBox(self.groupBox)
        self.originScale.setGeometry(QtCore.QRect(290, 20, 81, 21))
        self.originScale.setWrapping(False)
        self.originScale.setDecimals(7)
        self.originScale.setMinimum(1e-06)
        self.originScale.setMaximum(1.0)
        self.originScale.setSingleStep(0.0001)
        self.originScale.setProperty(_fromUtf8("value"), 0.9996)
        self.originScale.setObjectName(_fromUtf8("originScale"))
        self.label2 = QtGui.QLabel(self.groupBox)
        self.label2.setGeometry(QtCore.QRect(220, 18, 71, 24))
        self.label2.setObjectName(_fromUtf8("label2"))
        self.falseEastingField = QtGui.QDoubleSpinBox(self.groupBox)
        self.falseEastingField.setGeometry(QtCore.QRect(110, 50, 81, 20))
        self.falseEastingField.setWrapping(False)
        self.falseEastingField.setDecimals(0)
        self.falseEastingField.setMinimum(0.0)
        self.falseEastingField.setMaximum(1000000.0)
        self.falseEastingField.setSingleStep(10000.0)
        self.falseEastingField.setObjectName(_fromUtf8("falseEastingField"))
        self.label5 = QtGui.QLabel(self.groupBox)
        self.label5.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.label5.setObjectName(_fromUtf8("label5"))
        self.label6 = QtGui.QLabel(self.groupBox)
        self.label6.setGeometry(QtCore.QRect(10, 80, 91, 21))
        self.label6.setObjectName(_fromUtf8("label6"))
        self.falseNorthingField = QtGui.QDoubleSpinBox(self.groupBox)
        self.falseNorthingField.setGeometry(QtCore.QRect(110, 80, 81, 20))
        self.falseNorthingField.setWrapping(False)
        self.falseNorthingField.setDecimals(0)
        self.falseNorthingField.setMinimum(0.0)
        self.falseNorthingField.setMaximum(10000000.0)
        self.falseNorthingField.setSingleStep(10000.0)
        self.falseNorthingField.setObjectName(_fromUtf8("falseNorthingField"))
        self.label5_2 = QtGui.QLabel(self.groupBox)
        self.label5_2.setGeometry(QtCore.QRect(200, 50, 51, 21))
        self.label5_2.setObjectName(_fromUtf8("label5_2"))
        self.label5_3 = QtGui.QLabel(self.groupBox)
        self.label5_3.setGeometry(QtCore.QRect(200, 80, 51, 21))
        self.label5_3.setObjectName(_fromUtf8("label5_3"))
        self.label5_4 = QtGui.QLabel(self.groupBox)
        self.label5_4.setGeometry(QtCore.QRect(10, 110, 211, 21))
        self.label5_4.setObjectName(_fromUtf8("label5_4"))
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(10, 450, 381, 20))
        self.progressBar.setProperty(_fromUtf8("value"), 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.transformBtn = QtGui.QPushButton(Dialog)
        self.transformBtn.setEnabled(False)
        self.transformBtn.setGeometry(QtCore.QRect(230, 420, 75, 21))
        self.transformBtn.setObjectName(_fromUtf8("transformBtn"))
        self.layerProjectionDisplay = QtGui.QPlainTextEdit(Dialog)
        self.layerProjectionDisplay.setEnabled(True)
        self.layerProjectionDisplay.setGeometry(QtCore.QRect(10, 60, 381, 131))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.layerProjectionDisplay.setFont(font)
        self.layerProjectionDisplay.setUndoRedoEnabled(False)
        self.layerProjectionDisplay.setReadOnly(True)
        self.layerProjectionDisplay.setPlainText(_fromUtf8(""))
        self.layerProjectionDisplay.setObjectName(_fromUtf8("layerProjectionDisplay"))
        self.label4 = QtGui.QLabel(Dialog)
        self.label4.setGeometry(QtCore.QRect(20, 40, 251, 21))
        self.label4.setObjectName(_fromUtf8("label4"))
        self.saveFilePath = QtGui.QLineEdit(Dialog)
        self.saveFilePath.setGeometry(QtCore.QRect(10, 210, 291, 21))
        self.saveFilePath.setObjectName(_fromUtf8("saveFilePath"))
        self.fileDialogBtn = QtGui.QPushButton(Dialog)
        self.fileDialogBtn.setGeometry(QtCore.QRect(310, 210, 75, 21))
        self.fileDialogBtn.setObjectName(_fromUtf8("fileDialogBtn"))
        self.label7 = QtGui.QLabel(Dialog)
        self.label7.setGeometry(QtCore.QRect(10, 190, 251, 21))
        self.label7.setObjectName(_fromUtf8("label7"))
        self.checkBox = QtGui.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(10, 240, 211, 16))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.okOrCancel, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.okOrCancel, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "TransMerc", None, QtGui.QApplication.UnicodeUTF8))
        self.label0.setText(QtGui.QApplication.translate("Dialog", "Convert Layer of", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Gauss-Kruger Transformation Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label1.setText(QtGui.QApplication.translate("Dialog", "Central Meridian", None, QtGui.QApplication.UnicodeUTF8))
        self.label2.setText(QtGui.QApplication.translate("Dialog", "Scale Factor", None, QtGui.QApplication.UnicodeUTF8))
        self.label5.setText(QtGui.QApplication.translate("Dialog", "False Easting", None, QtGui.QApplication.UnicodeUTF8))
        self.label6.setText(QtGui.QApplication.translate("Dialog", "False Northing", None, QtGui.QApplication.UnicodeUTF8))
        self.label5_2.setText(QtGui.QApplication.translate("Dialog", "(metres)", None, QtGui.QApplication.UnicodeUTF8))
        self.label5_3.setText(QtGui.QApplication.translate("Dialog", "(metres)", None, QtGui.QApplication.UnicodeUTF8))
        self.label5_4.setText(QtGui.QApplication.translate("Dialog", "(Reference spheroid is fixed to WGS84)", None, QtGui.QApplication.UnicodeUTF8))
        self.transformBtn.setText(QtGui.QApplication.translate("Dialog", "Transform", None, QtGui.QApplication.UnicodeUTF8))
        self.label4.setText(QtGui.QApplication.translate("Dialog", "Coordinate Reference System of Selected Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.fileDialogBtn.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label7.setText(QtGui.QApplication.translate("Dialog", "Save the output to", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Dialog", "Load the output to current project", None, QtGui.QApplication.UnicodeUTF8))

